# Generated by Django 6.1.1 on 2026-09-27 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Продано штук')),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена продажи за 1 шт.')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма продажи')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Прибыль с продажи')),
                ('loss', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Убыток с продажи')),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sold_at'],
            },
        ),
    ]
