# Generated by Django 6.1.1 on 2026-09-27 11:17

import django.core.validators
import django.db.models.deletion
import products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_image_size], verbose_name='Фото товара')),
                ('arrival_date', models.DateField(verbose_name='Дата поступления')),
                ('quantity_received', models.PositiveIntegerField(default=0, verbose_name='Поступило (шт.)')),
                ('quantity_sold', models.PositiveIntegerField(default=0, verbose_name='Продано (шт.)')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Закупочная цена за 1 шт.')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена продажи за 1 шт.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
